### ISSUE TITLE
Trouble using between localhost:3001 and mLabs (Heroku)?

### ISSUE THREAD

**Issue by deborah-ufw** [sheharyarn/mongo-sync#12]
Hello,

I have free Mongo DB plugin mLabs on my Heroku instance with very light data (don't want to upgrade to paid Mongo DB from Mongo HQ).

I set up my config as follows, double-checking all the values were correct:

```
local:
  db: 'meteor'
  host: 
    port: 3001 /*also tried 27017*/

remote:
  db: 'heroku_6l0rt5bm'
  host:
    url: 'mongodb://heroku_6l0rt5bm:mysupersecurepassword@ds059155.mlab.com:59155/heroku_6l0rt5bm'
    port: 59155
  access:
    username: 'heroku_6l0rt5bm'
    password: 'mysupersecurepassword'
```

But running `./mongo-sync push` failed with error "Incorrect input, aborting..."

Have I accidentally left something out or done something funky, or is it possible to use the script for my case?

**Comment by sheharyarn** [comment]
@deborah-ufw You need to break down your remote mongodb `url` into individual parameters, so even though you didn't write your password in the sample above, I can still see it in the url. (Don't worry, I edited it to hide it).

It should be this:

``` yaml
local:
  db: 'local_db_name'
  host:
    port: 27017

remote:
  db: 'heroku_6l0rt5bm'
  host:
    url: 'ds059155.mlab.com'
    port: 59155
  access:
    username: 'heroku_6l0rt5bm'
    password: 'mysupersecurepassword'
```
